name: helm release

on:
  push:
    branches:
      - PhilippKuntschik-patch-2
    tags:
      - '*'

jobs:
  dispatch_helm_release:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch inscriptis-helm
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.HELMREPO_ACCESS_TOKEN }}
          repository: weblyzard/inscriptis-helm
          event-type: tag-released
          client-payload: '{"ref": "${{ github.ref_name }}"}'
